language: rust
rust:
  - 1.32.0
  - stable
script:
  - rustup component add clippy
  - rustup component add rustfmt
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --verbose --features "opq reductive/openblas"
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings
matrix:
  allow_failures:
    - rust: nightly
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libopenblas-dev
      - gfortran
